# Apollo AgriVerse

## Hydrogel Dataset Validation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Raw/hydrogel.csv")

df.head()

,timestamp,farm_id,water_storage,release_rate,remaining_capacity,status
0,2026-01-01 00:00:00,F0103,28.13,0.67,71.87,Low
1,2026-01-01 00:05:00,F0436,33.87,1.57,66.13,Low
2,2026-01-01 00:10:00,F0861,25.28,0.96,74.72,Low
3,2026-01-01 00:15:00,F0271,18.61,1.96,81.39,Critical
4,2026-01-01 00:20:00,F0107,47.72,0.68,52.28,Low

In [3]:
df.shape

(10000, 6)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   timestamp           10000 non-null  str
 1   farm_id             10000 non-null  str
 2   water_storage       10000 non-null  float64
 3   release_rate        10000 non-null  float64
 4   remaining_capacity  10000 non-null  float64
 5   status              10000 non-null  str
dtypes: float64(3), str(3)
memory usage: 759.8 KB

In [5]:
df.describe()

       water_storage  release_rate  remaining_capacity
count   10000.000000  10000.000000        10000.000000
mean       55.023917      2.345325           44.976083
std        25.945089      1.241378           25.945089
min        10.010000      0.200000            0.010000
25%        32.952500      1.270000           22.797500
50%        55.220000      2.330000           44.780000
75%        77.202500      3.420000           67.047500
max        99.990000      4.500000           89.990000

In [6]:
df.isnull().sum()

timestamp             0
farm_id               0
water_storage         0
release_rate          0
remaining_capacity    0
status                0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
print(df["water_storage"].min(), df["water_storage"].max())
print(df["release_rate"].min(), df["release_rate"].max())
print(df["remaining_capacity"].min(), df["remaining_capacity"].max())
print(df["status"].value_counts())

10.01 99.99
0.2 4.5
0.01 89.99
status
Healthy     5563
Low         3313
Critical    1124
Name: count, dtype: int64

In [9]:
df = df.drop_duplicates()

df.to_csv("../Cleaned/hydrogel_clean.csv", index=False)

print("Clean dataset saved.")

Clean dataset saved.