# Apollo AgriVerse

## Mulching Dataset Validation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Raw/mulching.csv")

df.head()

,timestamp,farm_id,mulch_type,degradation_percent,evaporation_reduction,temperature_reduction,status
0,2026-01-01 00:00:00,F0103,Plastic,10.97,23.69,4.51,Healthy
1,2026-01-01 00:05:00,F0436,Plastic,31.89,32.80,1.68,Healthy
2,2026-01-01 00:10:00,F0861,Plastic,17.63,58.82,2.79,Healthy
3,2026-01-01 00:15:00,F0271,Plastic,40.84,36.90,2.84,Needs Replacement
4,2026-01-01 00:20:00,F0107,Plastic,11.16,43.36,6.68,Healthy

In [3]:
df.shape

(10000, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   timestamp              10000 non-null  str
 1   farm_id                10000 non-null  str
 2   mulch_type             10000 non-null  str
 3   degradation_percent    10000 non-null  float64
 4   evaporation_reduction  10000 non-null  float64
 5   temperature_reduction  10000 non-null  float64
 6   status                 10000 non-null  str
dtypes: float64(3), str(4)
memory usage: 963.5 KB

In [5]:
df.describe(include="all")

,timestamp,farm_id,mulch_type,degradation_percent,evaporation_reduction,temperature_reduction,status
count,10000,10000,10000,10000.000000,10000.000000,10000.000000,10000
unique,10000,1000,3,NaN,NaN,NaN,3
top,2026-01-01 00:00:00,F0726,Plastic,NaN,NaN,NaN,Healthy
freq,1,22,4976,NaN,NaN,NaN,4069
mean,NaN,NaN,NaN,49.892019,40.032604,4.263573,NaN
std,NaN,NaN,NaN,28.868468,14.425009,1.879036,NaN
min,NaN,NaN,NaN,0.000000,15.000000,1.000000,NaN
25%,NaN,NaN,NaN,24.870000,27.640000,2.660000,NaN
50%,NaN,NaN,NaN,49.475000,40.190000,4.250000,NaN
75%,NaN,NaN,NaN,74.912500,52.490000,5.902500,NaN
max,NaN,NaN,NaN,99.980000,65.000000,7.500000,NaN

In [6]:
df.isnull().sum()

timestamp                0
farm_id                  0
mulch_type               0
degradation_percent      0
evaporation_reduction    0
temperature_reduction    0
status                   0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
print(df["mulch_type"].value_counts())
print(df["status"].value_counts())

mulch_type
Plastic          4976
Organic          3021
Biodegradable    2003
Name: count, dtype: int64
status
Healthy              4069
Needs Replacement    3449
Damaged              2482
Name: count, dtype: int64

In [9]:
print(df["degradation_percent"].min(), df["degradation_percent"].max())
print(df["evaporation_reduction"].min(), df["evaporation_reduction"].max())
print(df["temperature_reduction"].min(), df["temperature_reduction"].max())

0.0 99.98
15.0 65.0
1.0 7.5

In [10]:
df = df.drop_duplicates()

df.to_csv("../Cleaned/mulching_clean.csv", index=False)

print("Clean dataset saved.")

Clean dataset saved.