# Apollo AgriVerse

## Sensor Stream Validation

Purpose:
Validate the generated synthetic sensor dataset before integration into the master dataset.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Raw/sensor_stream.csv")

df.head()

,timestamp,farm_id,temperature,humidity,soil_moisture,soil_temperature,light_intensity,battery_level
0,2026-01-01 00:00:00,F0103,22.03,41.03,27.17,25.79,10693,79.82
1,2026-01-01 00:05:00,F0436,23.30,52.54,39.92,17.08,74120,46.16
2,2026-01-01 00:10:00,F0861,21.40,44.70,76.35,20.52,14378,67.29
3,2026-01-01 00:15:00,F0271,19.91,57.46,45.66,20.67,54217,52.83
4,2026-01-01 00:20:00,F0107,26.38,41.14,54.71,32.46,15655,74.25

In [3]:
df.shape

(10000, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         10000 non-null  str
 1   farm_id           10000 non-null  str
 2   temperature       10000 non-null  float64
 3   humidity          10000 non-null  float64
 4   soil_moisture     10000 non-null  float64
 5   soil_temperature  10000 non-null  float64
 6   light_intensity   10000 non-null  int64
 7   battery_level     10000 non-null  float64
dtypes: float64(5), int64(1), str(2)
memory usage: 859.5 KB

In [5]:
df.describe()

,temperature,humidity,soil_moisture,soil_temperature,light_intensity,battery_level
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,28.005323,62.440572,50.045687,25.041713,43038.471800,70.279450
std,5.765575,15.877632,20.195039,5.781601,24296.112586,17.326191
min,18.000000,35.000000,15.000000,15.000000,1001.000000,40.000000
25%,23.100000,48.680000,32.700000,20.120000,21820.500000,55.350000
50%,28.050000,62.210000,50.265000,25.000000,43121.500000,70.265000
75%,32.930000,76.202500,67.490000,30.090000,64209.750000,85.482500
max,38.000000,89.990000,85.000000,35.000000,84996.000000,99.990000

In [6]:
df.isnull().sum()

timestamp           0
farm_id             0
temperature         0
humidity            0
soil_moisture       0
soil_temperature    0
light_intensity     0
battery_level       0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
print(df["temperature"].min(),df["temperature"].max())
print(df["humidity"].min(),df["humidity"].max())
print(df["soil_moisture"].min(),df["soil_moisture"].max())
print(df["battery_level"].min(),df["battery_level"].max())

18.0 38.0
35.0 89.99
15.0 85.0
40.0 99.99

In [9]:
df = df.drop_duplicates()

df.to_csv("../Cleaned/sensor_stream_clean.csv",index=False)

print("Clean dataset saved.")

Clean dataset saved.